# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.200
    - name: Restore dependencies
      run: dotnet restore ./Source/Utilities.sln
    - name: Build
      run: dotnet build ./Source/Utilities.sln --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 9.0.200
     - name: Restore dependencies
       run: dotnet restore ./Source/Utilities.sln
     - name: Build
       run: dotnet build ./Source/UtilitiesTest/UtilitiesTest.csproj --no-restore
     - name: Test
       run: dotnet test ./Source/UtilitiesTest/UtilitiesTest.csproj --no-build --verbosity normal
    
